### ISSUE TITLE
如何在 css 样式文件内修改图标颜色

### ISSUE THREAD

**Issue by dominicleo** [iconfont-cli/remax-iconfont-cli#2]

**Comment by fwh1990** [comment]
图标底层是使用svg实现的，css样式无法生效，只能通过参数传递 

`<IconA color={['#fff', '#000']} />`

**Comment by fwh1990** [comment]
您也可以在iconfont.cn网站中提前对图标进行染色处理，这样就不需要传递color了

**Comment by dominicleo** [comment]
既然用 iconfont，就是希望图标能够复用嘛，所以是不是可以新增导入模式 Unicode、Font class，让开发者自行选择

**Comment by fwh1990** [comment]
需要明确的是，**字体不支持多色彩**！不然也不用大费周章做成svg路径了
